[server]
port = 4202
bind_address = "0.0.0.0"
agent_id = "bidirectional-agent-3"
agent_name = "Agent Three"

[client]
target_url = "http://localhost:4201"

[llm]
# API key set via environment variable
system_prompt = "You are an expert data analysis agent. When you receive tasks from Agent Two, perform the analysis and return detailed results. Always mention that you are Agent Three in your responses."

[mode]
repl = true
get_agent_card = false
repl_log_file = "delegation_interactions.log"

[tools]
enabled = ["echo", "summarize", "list_agents"]
agent_directory_path = "./data/agent3_directory.json"
