[server]
port = 4201
bind_address = "0.0.0.0"
agent_id = "bidirectional-agent-2"
agent_name = "Agent Two"

# [client]
# target_url = "http://localhost:4200"

[llm]
# API key set via environment variable
system_prompt = "You are a network coordination agent that maintains awareness of available agent services. Your primary function is to connect requestors with the right specialized agents based on the task requirements."

[mode]
repl = true
get_agent_card = false
repl_log_file = "shared_agent_interactions.log"

[tools]
enabled = ["echo", "llm", "list_agents", "execute_command", "remember_agent"]
# REMOVED agent_directory_path
