[server]
port = 4200
bind_address = "0.0.0.0"
agent_id = "bidirectional-agent-1"

[client]
target_url = "http://localhost:4201"

[llm]
# API key set via environment variable
system_prompt = "You are an AI agent that can communicate with other agents."

[mode]
repl = true
