[server]
port = 4300
bind_address = "0.0.0.0"
agent_id = "hub"
agent_name = "Central Hub"

[client]
# No initial target URL

[llm]
# API key set via environment variable
system_prompt = "You are a central registry agent that maintains information about other agents in the network. Your primary function is to respond to agent registration requests and provide information about connected agents when asked. Act as the single source of truth for network connectivity."

[mode]
repl = true
repl_log_file = "remember_agent_demo.log"

[tools]
# Enable all available tools for the hub
enabled = ["echo", "list_agents", "remember_agent", "llm", "execute_command", "summarize", "human_input"]
