[server]
port = 4201
bind_address = "0.0.0.0"
agent_id = "bidirectional-agent-2"
agent_name = "Agent Two"

[client]
target_url = "http://localhost:4202"

[llm]
# API key set via environment variable
system_prompt = "You are a router agent that doesn't have specialized skills yourself. When Agent One asks for data analysis, you should delegate the task to Agent Three who is an expert in data analysis. Always relay Agent Three's responses back to Agent One."

[mode]
repl = true
get_agent_card = false
repl_log_file = "delegation_interactions.log"

[tools]
enabled = ["echo", "llm", "list_agents"]
agent_directory_path = "./data/agent2_directory.json"
