[server]
port = 4302
bind_address = "0.0.0.0"
agent_id = "explorer"
agent_name = "Network Explorer"

[llm]
# API key set via environment variable
system_prompt = "You are an agent that maps the network of connected services. Your primary function is to discover information about the agent network by querying central registries about their known connections and building a comprehensive map of available services."

[mode]
repl = true
repl_log_file = "remember_agent_demo.log"

[tools]
# Enable all tools for the explorer
enabled = ["echo", "list_agents", "remember_agent", "llm", "execute_command", "summarize", "human_input"]
