[server]
port = 4202
bind_address = "0.0.0.0"
agent_id = "bidirectional-agent-3"
agent_name = "Agent Three -- can remember"

# [client]
# target_url = "http://localhost:4201"

[llm]
# API key set via environment variable
system_prompt = "You are an AI agent specialized in remembering other agents and relaying that information to other agents when requested"

[mode]
repl = true
get_agent_card = false
repl_log_file = "shared_agent_interactions.log"

[tools]
enabled = ["echo", "summarize", "list_agents", "remember_agent", "execute_command", "llm"] # <-- Add execute_command
# REMOVED agent_directory_path
