[server]
port = 4301
bind_address = "0.0.0.0"
agent_id = "seeker"
agent_name = "Knowledge Seeker"


[llm]
# API key set via environment variable
system_prompt = "You are the Knowledge Seeker agent. Your role is to ask other agents to remember you, and to query other agents for information. You specialize in initiating connections with new agents."

[mode]
repl = true
repl_log_file = "remember_agent_demo.log"

[tools]
# Enable all tools for the seeker as well
enabled = ["echo", "list_agents", "remember_agent", "llm", "execute_command", "summarize", "human_input"]
