[server]
port = 4200
bind_address = "0.0.0.0"
agent_id = "bidirectional-agent-1"
agent_name = "Agent One"

[client]
target_url = "http://localhost:4201"

[llm]
# API key set via environment variable
system_prompt = "You are a helpful assistant agent that relies on other agents to accomplish tasks. When you need data analysis, ask Agent Two for help."

[mode]
repl = true
get_agent_card = false
repl_log_file = "delegation_interactions.log"

[tools]
enabled = ["echo", "llm", "list_agents"]
agent_directory_path = "./data/agent1_directory.json"
