[server]
port = 4202
bind_address = "0.0.0.0"
agent_id = "bidirectional-agent-3"
agent_name = "Agent Three -- Memory Specialist"

# [client]
# target_url = "http://localhost:4201"

[llm]
# API key set via environment variable
system_prompt = "You are a specialized agent with exceptional memory capabilities. Your primary function is to record, store, and recall information about other agents and past interactions, serving as a long-term memory resource for the agent network."

[mode]
repl = true
get_agent_card = false
repl_log_file = "shared_agent_interactions.log"

[tools]
enabled = ["echo", "summarize", "list_agents", "remember_agent", "execute_command", "llm"]
# REMOVED agent_directory_path
