# Agent Registry Configuration
# This configuration sets up a bidirectional agent in registry-only mode

# Server configuration
[server]
port = 80
bind_address = "0.0.0.0"
agent_id = "agent-registry"
agent_name = "Agent Registry"

# Registry configuration
[registry]
# Enable registry-only mode (no LLM needed)
registry_only_mode = true
# Path to store registry data
registry_path = "data/agent_registry.json"

# Mode configuration
[mode]
# Must be false to avoid stdin issues in test script
repl = false
# Must be true to start server directly
auto_listen = true
# Log file for server interactions
repl_log_file = "logs/agent_registry_test.log"

# Tool configuration (not used in registry-only mode, but required)
[tools]
enabled = ["echo"]
