[server]
port = 4200
bind_address = "0.0.0.0"
agent_id = "bidirectional-agent-1"
agent_name = "Agent One"

# [client]
# target_url = "http://localhost:4201"

[llm]
# API key set via environment variable
system_prompt = "You are a multi-purpose agent that discovers and connects with other agents. Your primary role is to identify when you need assistance from specialized agents and establish connections with them to solve complex tasks collaboratively."

[mode]
repl = true
get_agent_card = false
repl_log_file = "shared_agent_interactions.log"

[tools]
enabled = ["echo", "llm", "list_agents", "execute_command", "remember_agent"]
# REMOVED agent_directory_path
