[server]
port = 4201
bind_address = "0.0.0.0"
agent_id = "bidirectional-agent-2"
agent_name = "Agent Two"

# [client]
# target_url = "http://localhost:4200"

[llm]
# API key set via environment variable
system_prompt = "You are an expert agent-discovery and routing agent. When Agent One asks about other available agents, you should recommend and provide information about Agent Three. Agent Three is an expert in data analysis tasks."

[mode]
repl = true
get_agent_card = false
repl_log_file = "shared_agent_interactions.log"

[tools]
enabled = ["echo", "llm", "list_agents", "execute_command"]
# REMOVED agent_directory_path
